name: Build Vue
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'rate-my-drink'
        reponame: 'rate-my-drink.github.io'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
